apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: frontend 
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: frontend 
 template: 
   metadata: 
    labels: 
     app: frontend
     env: prod 
   spec: 
    containers: 
    - name: frontend 
      image: chaimakh/frontend:latest
