apiVersion: v1
kind: Service
metadata:
 name: frontend
spec:
 type: NodePort
 selector:
   app: frontend
   env: prod
 ports:
 - name: test1
   protocol: TCP
   port: 80
   targetPort: 80
   nodePort: 30000
